[package]
name = "rent-machine-runtime-api"
version = "0.1.0"
authors = ["bobo"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
rent-machine = { version = "0.1.0", path = "../../../rent-machine", default-features = false }

[dependencies.sp-api]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353'
version = '3.0.0'

[dependencies.sp-runtime]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353'
version = '3.0.0'

[dependencies.sp-std]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353'
version = '3.0.0'

[dependencies.generic-func]
default-features = false
path = '../../../generic-func'
package = 'generic-func'

[features]
default = ["std"]
std = [
    "codec/std",
    "rent-machine/std",
    "sp-api/std",
    "sp-runtime/std",
    "sp-std/std",
    "generic-func/std",
]
